version: 1

python-targets:
  - 3.8

javascript:
  processor:
    eslint:
      enabled: true
    prettier:
      enabled: true

typescript:
  processor:
    eslint:
      enabled: true

exclude_patterns:
  - node_modules/**
  - dist/**
  - coverage/**
  - "**/*.test.ts"
  - test/**
  - docs/**
  - "**/*.d.ts"
